# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
# modyfikacja testowa w celu sprawdzenia połączenia z SonarCloud

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCheck'
    organization: 'zpisonar'
    scannerMode: 'Other'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '**/coverage-reports/jacoco-unit.exec'
    reportDirectory: '**/site/jacoco/*.xml'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
